### PR TITLE
Add a module to fetch leader information cluster

### PR DESCRIPTION
**Pull request by Dudesons**

### CODE REVIEW

**Comment by TerryHowe** [comment]
Thanks

**Comment by Dudesons** [comment]
@TerryHowe do you have an ETA to generate the next release ?

**Comment by TerryHowe** [comment]
I was going to look at the other one and maybe attempt to add some functional tests even if the result is failure on the container.  I have $DAY_JOB to deal with today, but should cut a release in the next couple.

**Comment by TerryHowe** [comment]
I added a functional test for each of these and made a change

https://github.com/TerryHowe/ansible-modules-hashivault/commit/f497997286d83643bf9e988d9a046b21099d7ccb#diff-715abf80aa026fcacc1ef94414e0b1ef

My non clustered Dockerized vault returns and empty string. Hvac 0.7.2 returns a requests.model.Response I'm not sure if you were seeing something else.

**Pull request merged**
