### PR TITLE
drewmullen/issue-129 - azure secret engine

### PR DESCRIPTION
**Pull request by drewmullen**
this PR allows passing AnsibleModule vars:
- `required_if`
- `required_together`
- `required_one_of`
- `mutually_exclusive`

more info can be found [here](http://mobygeek.net/blog/2016/02/16/ansible-module-development-parameters/)

this PR also creates a new ansible module `hashivault_azure_secret_engine_config` which takes azure SPN creds as an input from either yaml or as a json file and configures an `azure` secret engine.

this PR also creates a new ansible module `hashivault_azure_secret_engine_role` which defines azure roles in a vault azure secret engine for dynamic credentialing

**testing**
functional/test_azure_config.yml
functional/test_azure_role.yml <- disabled due to reliance on azure credentials

https://github.com/TerryHowe/ansible-modules-hashivault/issues/129

### CODE REVIEW

**Comment by drewmullen** [comment]
not sure whats going on with the doc failure above, any advice?

moving onto unit testing. my thought was to first get the class to execute the command then start subbing out parts until we're left with no actual api calls.

```
import unittest
import hashivault_azure_secret_engine_config as h

case = {'params': {'subscription_id': 'blergh', 'client_id': 'foo', 'client_secret': 'bar', 'tenant_id': 'fie', 'url': 'https://vault.example.com:8200', 'ca_cert': '', 'ca_path': '', 'client_cert': '', 'client_key': '', 'verify': False, 'authtype': 'token', 'token': 'blergh', 'username': '', 'password': '', 'role_id': '', 'secret_id': '', 'mount_point': 'azure', 'environment': 'AzurePublicCloud', 'namespace': None, 'config_file': None}}

class TestAzureConfig(unittest.TestCase):

    
    def test_print(self):
        result = h.hashivault_azure_secret_engine_config(case)
        print(result)

if __name__ == '__main__':
    unittest.main()
```
when i pass this though im getting `test_print (__main__.TestAzureConfig) ... {'changed': False, 'rc': 1, 'failed': True, 'msg': "Exception: 'dict' object has no attribute 'params'"}`

**Comment by TerryHowe** [comment]
The docs issue is the accent graves on azure, needs to be single quotes or nothing.

**Comment by drewmullen** [comment]
so i realized we actually **can** test the azure engine **enablement** with fake values. we just cant verify it actually connects to someones azure instance without real values. however, i dont think thats required in the scope of this library since our goals is only enabling.

can you take a look at the failed test. these are actually executing against a vault node, right? `hashivault_secret_enable` is completing successfully, according to the log. so i assume the engine should actually be enabled (but not configured yet). but then the config fails when i do a pre-check 

```
# check if engine is enabled
client.sys.list_auth_methods().keys()
if (mount_point + "/") not in client.sys.list_auth_methods().keys():
     return {'failed': True, 'msg': 'auth backend is not enabled', 'rc': 1}
```

again, these tests pass on my local env

**Comment by drewmullen** [comment]
is it supposed to communicate on `8201`?
`"url": "http://127.0.0.1:8201",`

**Comment by drewmullen** [comment]
i see it. the test is for `auth`, should be secret. got false positives locally because I happen to have an azure auth backend enabled.

pushing a fix

**Comment by drewmullen** [comment]
I'm not sure whats up with the documentation job but @TerryHowe otherwise these are good to go

ive included the testing for `_role` module so you can see my testing logic and so its at least documented... however, we cannot enable those tests to run unless the `v1/azure/config` is set and actually works. the `_config` is be auto-tested because it never reaches to azure, but the role cannot.

**Comment by TerryHowe** [comment]
Looks good in general, I'm going to merge and mess with it a little to get a feel for it.

**Comment by TerryHowe** [comment]
Thanks!

**Pull request merged**
