### PR TITLE
Conversion to Ansible Collection

### PR DESCRIPTION
**Pull request by onitake**
This PR converts the module into an Ansible collection.

Fixes: #234

Still to do: Update the documentation and remove PyPi scripts.

It can be packaged with:
```shell
ansible-galaxy collection build
```
The package can then be installed into the user's home with:
```shell
ansible-galaxy collection install terryhowe-hashivault-4.5.2.tar.gz
```

To try it out, use the following playbook:
```yaml
- hosts: test
  gather_facts: no
  collections:
   - terryhowe.hashivault
  tasks:
  - name: get test secret
    delegate_to: localhost
    hashivault_read:
      secret: test/secret
    register: new
  - debug:
      var: new.value
```

### CODE REVIEW

**Comment by TerryHowe** [comment]
Somehow I missed the notification on this PR, I need to look at this.

**Comment by teamosceola** [comment]
I would really like to see this conversion to a collection happen!

**Comment by freeseacher** [comment]
Any updates on this pr?

**Comment by TerryHowe** [comment]
I've cleared up the other issues and started working on this, but there is a lot for me to understand here.

**Comment by dr4Ke** [comment]
You should probably get rid of the `hashivault_` prefix on all modules, in the process. Modules would be used in the `terryhowe.hashivault.secret` form instead of `terryhowe.hashivault.hashivault_secret`.

It seems possible to still support `hashivault_` prefix for backward playbook compatibility. See https://opendev.org/openstack/ansible-collections-openstack/src/commit/94e518e42c3d08e227df1dcf2b9a2aad4429f00d/plugins/modules/server_info.py#L65

**Comment by dr4Ke** [comment]
You should probably get rid of the `hashivault_` prefix, in the process. This way, modules would be used in the form of `terryhowe.hashivault.secret` instead of `terryhowe.hashivault.hashivault_secret`

It should still be possible to support the previous names. See for example: https://opendev.org/openstack/ansible-collections-openstack/src/commit/94e518e42c3d08e227df1dcf2b9a2aad4429f00d/plugins/modules/server_info.py#L65

**Comment by TerryHowe** [comment]
I've fixed merge conflicts and pushed to a new branch https://github.com/TerryHowe/ansible-modules-hashivault/pull/315 but I'm going to leave this open a bit to get some more info out of this PR.

**Comment by absynth76** [comment]
must have :)

**Comment by TerryHowe** [comment]
Stale

**Pull request closed without merging**
