### PR TITLE
Ansible collection

### PR DESCRIPTION
**Pull request by TerryHowe**
This PR converts the module into an Ansible collection.

Fixes: #234
Closes: #263

Still to do: Update the documentation and remove PyPi scripts.

It can be packaged with:
```shell
ansible-galaxy collection build
```
The package can then be installed into the user's home with:
```shell
ansible-galaxy collection install terryhowe-hashivault-4.5.2.tar.gz
```

To try it out, use the following playbook:
```yaml
- hosts: test
  gather_facts: no
  collections:
   - terryhowe.hashivault
  tasks:
  - name: get test secret
    delegate_to: localhost
    hashivault_read:
      secret: test/secret
    register: new
  - debug:
      var: new.value
```

### CODE REVIEW

**Comment by onitake** [comment]
Looks like the tox tests will need to be adapted as well.
You could also add a "Closes: #263" to the description to have the other PR closed automatically when this gets merged.

In any case, thanks for looking into the PR. I'll give your modifications a try later.

**Comment by freeseacher** [comment]
@onitake any updates ?

**Comment by elcomtik** [comment]
I'm looking forward to completing this feature.

**Comment by bendem** [comment]
It looks like a bunch of symbols have been removing from `module_utils/hashivault.py` yet are still imported. Can this branch be maybe restarted from the latest changes (4.6.2) instead of try and replay the work that's gone into main, but untested and partial.

**Comment by ericsysmin** [comment]
Any updates on this?

**Comment by fastlorenzo** [comment]
> 
> 
> It looks like a bunch of symbols have been removing from `module_utils/hashivault.py` yet are still imported. Can this branch be maybe restarted from the latest changes (4.6.2) instead of try and replay the work that's gone into main, but untested and partial.

This can be done via a `git rebase`.

@TerryHowe any plans on having this converted to a collection and pushed to Ansible Galaxy?

**Comment by bendem** [comment]
> This can be done via a `git rebase`.

Have you checked out the branch? Someone did try to rebase it, it's a mess. Some symbols are used but their definitions disappeared, some stuff got merged one way some stuff got merged the other way...

**Comment by fastlorenzo** [comment]
> > This can be done via a `git rebase`.
> 
> Have you checked out the branch? Someone did try to rebase it, it's a mess. Some symbols are used but their definitions disappeared, some stuff got merged one way some stuff got merged the other way...

If you're talking about PR #350 , it's me 😆
I've tried something but not sure if the rebate all went well.

**Pull request merged**
