### PR TITLE
Fix the compatibility of the db role module with python 2.7

### PR DESCRIPTION
**Pull request by Dudesons**
Signed-off-by: Damien Goldenberg <damdam.gold@gmail.com>

related to #142

### CODE REVIEW

**Comment by TerryHowe** [comment]
LGTM, thanks, but I'm going to rekick travis to try and get a better idea what is going on there.  I can't seem to reproduce that problem locally.

**Comment by TerryHowe** [comment]
I scanned the rest of the code base for other prints and found nothing. Thanks for finding this.

**Comment by TerryHowe** [comment]
3.18.2

**Comment by drewmullen** [comment]
thanks @Dudesons i believe I heard someone talk about how ansible treats any stdout during a play as an error (non RC1) so this print statement could be causing that

**Pull request merged**
