### PR TITLE
Add enterprise configuration features seal_wrap and local to secrets

### PR DESCRIPTION
**Pull request by dave-dave**
Solves #326 
Tests included but deactivated

### CODE REVIEW

**Comment by dave-dave** [comment]
@TerryHowe looks like there's a break in GCP engine handling that  is unrelated. Would fixing that be part of this commit?

**Comment by TerryHowe** [comment]
Could you rebase. I think the problem was it is using hvac==1.0.0 which is breaking. I put in a change to limit to <1

**Comment by TerryHowe** [comment]
_hashivault_secret_enable.py is deprecated, no need to change that

**Comment by TerryHowe** [comment]
seal_wrap was added in another PR, but local does not exist.

**Pull request closed without merging**
