### PR TITLE
db engine config plugin can be used for all db plugins

### PR DESCRIPTION
**Pull request by Dudesons**
Signed-off-by: Damien Goldenberg <damdam.gold@gmail.com>

### CODE REVIEW

**Comment by Dudesons** [comment]
This pull request break the previous contract but I didn't find an elegant way to update the plugin to be used by all vault db plugins

**Comment by Dudesons** [comment]
@TerryHowe the test job fail on the test `idempotently create role` but it's a test related with azure

**Comment by drewmullen** [comment]
can you elaborate on the purpose of this change, please

**Comment by Dudesons** [comment]
The goal is to support non sql database backend like cassandra, elasticsearch ...
This database backend doesn't have connection `connection_url ` parameter in the plugin and have other parameters.
In my case I want to manage a scylladb with the cassandra plugin i have the following arguments: https://www.vaultproject.io/api/secret/databases/cassandra.html
I don't want to use a file, because I can't store a clear password.

**Comment by drewmullen** [comment]
**fun**. so the plugin params dont match...

as far as storing the pw in plain text, that isnt a problem with postgres because the password is immediately rotated. 

one other side note - thanks very much for the thoughtful contribution. it would be helpful for a better description next PR. something like "changing `db_username` and `connection_url` to nest in a new var `connection_details`. the highlights of the change and why, basically. 

otherwise, im good with this PR but i want to test the change first just to make sure it still works with a SQL db. unfortunately, that wont be till next week because i have to coordinate with a DBA to verify... ill report back asap

**Comment by Dudesons** [comment]
ok @drewmullen 
the only common parameters in the database secret engines are [here](https://www.vaultproject.io/api/secret/databases/index.html)

**Comment by drewmullen** [comment]
sorry for the delay - worked great! thanks for the contribution, @Dudesons !

**Comment by TerryHowe** [comment]
Thanks.

**Pull request merged**
