### PR TITLE
add ability to write a policy from a file

### PR DESCRIPTION
**Pull request by drewmullen**

### CODE REVIEW

**Comment by drewmullen** [comment]
the failed check doesnt appear to have anything to do with my changes. did i miss something?

```
TASK [hashivault_auth_enable] **************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Exception: path is already in use", "rc": 1}
PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=1   
ERROR: InvocationError for command '/bin/bash -ex /home/travis/build/TerryHowe/ansible-modules-hashivault/functional/run.sh' (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   py36: commands failed
The command "tox" exited with 1.
```

**Comment by TerryHowe** [comment]
The latest docker container running vault 0.11.0 is causing some issues with the tests (which I've fixed) and with hvac https://github.com/hvac/hvac/issues/263

**Comment by TerryHowe** [comment]
I may rename this to hashivault_policy_set_from_file to be more consistent, I want to mess around with it first.

**Comment by drewmullen** [comment]
That's fine

Lmk if you encounter any problems, I've been using it internally for a
couple weeks and no issues yet

**Comment by TerryHowe** [comment]
I added an automated functional test too https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/functional/test_policy.yml#L94 I'll cut a release this week sometime, thanks!

**Pull request merged**
