### PR TITLE
allows to create a aws ec2 backed vault role

### PR DESCRIPTION
**Pull request by simonmacklin**
This new feature will allow to create new aws backed auth roles.

### CODE REVIEW

**Comment by simonmacklin** [comment]
Sorry I need to change the test slightly.  I am testing for the AWS auth backend rather then the role being present after the execution.

I will fix this shortly

**Comment by simonmacklin** [comment]
Many thanks.  Yes I just realised there is a run.sh script that calls the functional tests individually and I had never added to it.  

Shall I add the tests I wrote to them?  

Simon

**Comment by TerryHowe** [comment]
As long as it can be run without proper aws creds because travis won't have that.

**Comment by simonmacklin** [comment]
Yes this code just creates the role and does not require any AWS credentials.

**Comment by simonmacklin** [comment]
Hi Terry

I was just wondering what you thought about having some logic to not just create roles but also update the attributes if they have changed.  I had a look at the other create role resources and the code just creates the role if it does not exists.  I was thinking about doing something like below but if you think its pointless let me know.  

```
try:
        role = client.get_role(name, 'aws')
        need_updating = False
        for k, v in role.data.items():
            if kwargs[k] != v:
                need_updating = True
                kwargs[k] = v
        if need_updating:
            create_role(name, mount_point='aws', **kwargs)
            return {'changed': True}
        else:
            return {'changed': False}

    except exceptions.InvalidPath:
        client.create_role(name, mount_point='aws', **kwargs)
        return {'changed': True}
```

**Comment by TerryHowe** [comment]
In general I like the modules to be idempotent and detect changes and properly report change=True/False.

I may rename this if I can think of a good naming convention to work with here.

**Comment by simonmacklin** [comment]
Please do I am terrible at coming up with good naming schemes.

**Comment by TerryHowe** [comment]
hashivault_aws_ec2_role_create is the new name, thanks!

**Comment by simonmacklin** [comment]
Perfect!

**Pull request merged**
