### PR TITLE
feature/read_and_write_file_secrets

### PR DESCRIPTION
**Pull request by nicholasgibson2**

### CODE REVIEW

**Comment by TerryHowe** [comment]
Sorry @nicholasgibson2 when you did the first PR I asked why you were doing this and I never understood the answer, but this is the reason https://github.com/ansible/ansible/issues/13794 Basically jinja2 does not support binary data.  

What I'm still wondering:

1. Is there some way to work around the jinja2 issue.  I think not, but wondering.
2. Why did you put them in action plugins?  
3. The names are very confusing because `hashivault_read_file` actually writes a file
4. Sometimes I wonder if `dest` could be added as a parameter to `hashivaul_read` I don't think so, but I wonder

I'll make some more time today to look at this.  I was messing with what you have over the weekend.

**Comment by nicholasgibson2** [comment]
1. I wanted to enforce the base64 encoding, so files can be written and read with the modules without having to worry about encoding.
2. The hashivault communication needs to happen on the Ansible host, and file manipulation needs to happen on the remote host(s).
3. I agree, we could rename `hashivault_read_file` and `hashivault_write_file` to `hashivault_download_file` and `hashivault_upload_file` respectively.
4. I don't understand this question.

**Comment by TerryHowe** [comment]
Okay your explanation on the action plugin kills number 4 anyway.  I was just considering what it would look like to add some destination type parameter to the `hashivault_read` module that would send the result to the destination.

I think `hashivault_download_file` is still a bit confusing though because you are really uploading a file to the destination.  Maybe something like `hashivault_copy_to_file` and `hashivault_copy_from_file`.  You hae anything better than that?

**Comment by nicholasgibson2** [comment]
Do the module names need to start with `hashivault`? Otherwise `download_file_from_hashivault` and `upload_file_to_hashivault` would be good names.

**Comment by TerryHowe** [comment]
Well, for consistency it would be best if they started with that.  *Everything* else does.

**Comment by nicholasgibson2** [comment]
`hashivault_download_file_from_vault` is a bit long. I think `hashivault_download_file` implies downloading the file from vault to the target host. It's at least an improvement over the current name, and users will consult the documentation first. My vote is still `hashivault_download_file` and `hashivault_upload_file`.

**Comment by TerryHowe** [comment]
Can you live with a command `hashivault_file_write` that reads from vault and writes a file and `hashivault_read_file` that reads a file and writes to vault?  With the noun before the verb I think it is a little clear what the verb is acting on.

**Comment by nicholasgibson2** [comment]
That is opposite logic though. The module with `write` in the name should be writing to Vault, and the module with `read` in the name should be reading from Vault. That is the naming logic for your existing read and write modules.

**Comment by TerryHowe** [comment]
`hashivaullt_read_to_file` and `hashivault_write_from_file` names seem long, but they are clearer

**Comment by TerryHowe** [comment]
I'll take no response on my last comment as either you accept that idea or you've given up on consensus. Those names seem to me most likely to be least offensive.

**Comment by TerryHowe** [comment]
Thanks @nicholasgibson2 hope you aren't too annoyed with me over the slow response here.  It took me a while to figure out why on this one.

**Comment by nicholasgibson2** [comment]
Hey @TerryHowe, no worries. I've been busy with work and haven't had a chance to respond. Thanks for getting it merged. By the way, your [blog post on Action Plugins](https://terryhowe.wordpress.com/2016/05/03/ansible-2-0-modules-and-action-plugins/) was very useful for developing this module.

**Pull request merged**
