### PR TITLE
Remove default value version, update dictionary comparison

### PR DESCRIPTION
**Pull request by SamyCoenen**

### CODE REVIEW

**Comment by TerryHowe** [comment]
The travis failure for py27 does seem related to this change. I haven't looked into it, but I'd guess there is something that works a bit different for 2.7. On one hand we shouldn't support 2.7, but I imagine there are a lot of people using 2.7 out there.

**Comment by TerryHowe** [comment]
https://travis-ci.org/TerryHowe/ansible-modules-hashivault/jobs/656456592?utm_medium=notification&utm_source=github_status

**Comment by SamyCoenen** [comment]
> The travis failure for py27 does seem related to this change. I haven't looked into it, but I'd guess there is something that works a bit different for 2.7. On one hand we shouldn't support 2.7, but I imagine there are a lot of people using 2.7 out there.

There is a difference between python 2 and python 3 using dictionary views https://docs.python.org/2/library/stdtypes.html#dictionary-view-objects
python 2 uses .viewitems() instead of .items()

**Comment by TerryHowe** [comment]
Ah, shoot, I messed up the merge on this. This modules is kind of messy. I was reluctant on this because I didn't want to add the dependency on six although it looks like something ansible uses requires six. Great package, I just don't want to increase dependencies

**Pull request merged**
