### PR TITLE
optionally include namespace as play parameter or environment var

### PR DESCRIPTION
**Pull request by drewmullen**
Vault enterprise allows for segmenting youre vault into 'mini-vaults' called Namespaces. this PR allows you allows you to take advantage of HVAC 0.7s ability to inject the namespace as a http header when creating the Client object

you can specify the namespace in 2 ways:
1. as a param in your ansible play
2. as an environment variable VAULT_NAMESPACE

tested execution on vault 1.0:
1. as a param in your ansible play
2. as an environment variable VAULT_NAMESPACE
3. with VAULT_NAMESPACE=""
4. without setting VAULT_NAMESPACE or namespace in play

### CODE REVIEW

**Comment by drewmullen** [comment]
@TerryHowe any idea on an ETA for this PR?

**Comment by TerryHowe** [comment]
Sorry for the delay, I got a bit overwhelmed with the holiday etc

**Comment by TerryHowe** [comment]
released 3.12

**Comment by drewmullen** [comment]
I hear you. If I get sometime I might look into a way to share them across
modules... Interesting problem

**Pull request merged**
